### ISSUE TITLE
/usr/bin/env: 'node\r': No such file or directory

### ISSUE THREAD

**Issue by ta69** [witoza/streambin.pl#1]
Running Ubuntu 16.04 gives error after attempting to

```
$ npm i --global streambin
$ streambin -h http://192.168.0.1/ -p 9001
/usr/bin/env: 'node\r': No such file or directory
```

I've tried with two node versions:

```
$ which node
/usr/bin/node
$ node -v
v4.2.6
```
and 
```
$ which node
/usr/local/bin/node
$ node -v
v6.4.0
```

Any ideas how to fix it?

**Comment by witoza** [comment]
Thanks for letting me know.

Yeah, it was linux vs windows newline issue, should be fixed now. 

Just update to the latest via "npm i --global streambin". Node 6.X is no good - they have some stream, WS issues, use 4.x instead.
