### ISSUE TITLE
cannot transfer file with CJK chars in filename

### ISSUE THREAD

**Issue by fliar** [witoza/streambin.pl#2]
when receiving a file with a name like this "C++模板元编程" shows this:

> TypeError: The header content contains invalid characters
>    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
>    at /home/ubuntu/apps/streambin.pl/_backend/index.js:250:9
>    at Layer.handle [as handle_request](/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/layer.js:95:5)
>    at next (/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/route.js:131:13)
>    at Route.dispatch (/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/route.js:112:3)
>    at Layer.handle [as handle_request](/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/layer.js:95:5)
>    at /home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/index.js:277:22
>    at param (/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/index.js:349:14)
>    at param (/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/index.js:365:14)
>    at Function.process_params (/home/ubuntu/apps/streambin.pl/_backend/node_modules/express/lib/router/index.js:410:3)

**Comment by witoza** [comment]
Thanks for letting me know, it should be fixed now.
